username = "Enter Spotify User ID"
client_id = "Enter Client ID"
client_secret = "Enter Client Secret"
redirect_uri = "Enter redirect_uri"
podcastName1 = "Enter first podcast title"
podcastName2 = "Enter second podcast title"
playlistName = "Enter the name of your own playlist"